01 lesson button
js-tasks-ru/htmlcss-20220317_mick911 pull request #3
Opened 2022-03-23 20:07 UTC by terentevm

решение задачи по стилизации кнопок

2022-03-23 20:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-23 22:06 UTC, GSemikozov requested changes

2022-03-23 22:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 15px;
по макету - `15px 15px 14px`

2022-03-23 22:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 15px;
и еще не хватает стилей описывающих текст

2022-03-23 22:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
при pointer-event: none; это будет лишним - курсор все равно будет cursor: default

2022-03-23 22:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: none;
этот сброс можно оформить сразу на уровне .button

2022-03-23 22:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: none;
чтобы в том числе не дублировать ниже

2022-03-23 22:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__title {
ага, понял почему нет описания стилей текста на уровне .button)
на самом деле кнопка у нас простой компонент, нет нужды в .button__title

2022-03-24 11:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-24 11:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-26 20:06 UTC, GSemikozov requested changes

2022-03-26 20:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: none;
все еще актуально

2022-03-26 20:06 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: none;
и тут

2022-03-26 20:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-26 20:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-26 20:25 UTC, GSemikozov approved these changes

2022-03-26 20:25 UTC, merged