01.2 accordion solution
js-tasks-ru/htmlcss-20220317_mick911 pull request #4
Opened 2022-03-28 11:45 UTC by terentevm

Решение задачи "Аккордион"

2022-03-28 11:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-28 12:00 UTC, GSemikozov requested changes

2022-03-28 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину и высоту не нужно жестко фиксировать (вообще указывать), тем более что анимирование изменения высоты сейчас не реализуется.

2022-03-28 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details > summary {
44-49 - селекторы тегов в БЭМ не используем, для этого у нас классы по БЭМ)

2022-03-28 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content p {
.accordion__content p -> .accordion__text

2022-03-28 12:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] {
перепутано - это на самом деле .accordion__item, а то что охватывает item-ы - .accordion (поскольку ребенок не может быть родителем родителя =))

2022-03-29 20:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-30 19:18 UTC, GSemikozov requested changes

2022-03-30 19:18 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
этот класс выше уже определен

2022-03-30 19:18 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item > .accordion__summary {
вложенные селекторы нет смысла использовать, название блока в начале имени класса само по себе делает безопасным задание стилей элемента

2022-03-30 19:18 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item > .accordion__summary::-webkit-details-marker {
и тут

2022-03-30 19:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-31 15:50 UTC, GSemikozov approved these changes

2022-03-31 15:50 UTC, merged